### ISSUE TITLE
Is it possible to just minify {{{ body }}}

### ISSUE THREAD

**Issue by NetOpWibby** [melonmanchan/express-minify-html#4]
Question is in the title. I want to keep the ASCII art in my `<head>` but would like to minify everything in `{{{ body }}}`.

EDIT: I know I could just wrap `<!-- htmlmin:ignore -->` around the content I don't want minified, but it'd be great if this was possible via parameters.

**Comment by melonmanchan** [comment]
Hi!

Sorry for the late reply, seems like I had accidentally missed this issue due to fiddling around with my notification settings.

Anyways, I don't think implementing this particular feature would be useful to many people, especially since the same can be achieved with the aforementioned `<!-- htmlmin:ignore -->` meta tags. I'd suggest just using those, or maybe injecting the ASCII art after the rest of the page content has been minified, but before sending it.

Thanks for using my humble little module!

**Comment by melonmanchan** [comment]
Alternatively, one way to keep your ASCII art unmangled would be to include it as a HTML comment, and then passing `removeComments: false`to the options (Which I believe is the default.) This also seems to preserve line breaks and such inside the comment tag according to quick testing.

**Comment by NetOpWibby** [comment]
I just wrapped the comment about the `<head>`, I'm fine with that. Thanks for making this thing!
